### ISSUE TITLE
Commit comments / messages are not helping much

### ISSUE THREAD

**Issue by ghost** [Luup850/Zephyr-drone#1]
Commit messages such as "." (https://github.com/Luup850/Zephyr-drone/commit/621b090404ee6310f9081016383de5b93df7edfb) are confusing and don't help me as an outsider to understand this open source code.
If you want the open source community to contribute, please document your code accordingly.

**Comment by Luup850** [comment]
Duly noted

- Luup

**Comment by Luup850** [comment]
Duly noted

- Luup
